[package]
name = "typex-pipeline"
version.workspace = true
edition.workspace = true

[dependencies]
typex-asr = { workspace = true }
typex-llm = { workspace = true }
typex-plugin = { workspace = true }
typex-injector = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
