[package]
name = "typex-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "typex"
path = "src/main.rs"

[dependencies]
typex-core = { workspace = true }
typex-asr = { workspace = true }
typex-llm = { workspace = true }
typex-pipeline = { workspace = true }
typex-injector = { workspace = true }
typex-config = { workspace = true }
typex-plugin = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
